// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'domainListItem': string;
  'domainsTitle': string;
  'submitButtonCreate': string;
}
export const cssExports: CssExports;
export default cssExports;
