// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-typography': string;
  'copyPre': string;
  'hoverButton': string;
}
export const cssExports: CssExports;
export default cssExports;
