// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'domainHeaderContainer': string;
  'domainSubtitle': string;
  'domainTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
