// This file is automatically generated.
// Please do not change this file!
interface CssExports {
	'loginLogo': string;
	'loginLogoWrap': string;
	'loginSubtitle': string;
	'loginTitle': string;
	'oauthImg': string;
}
export const cssExports: CssExports;
export default cssExports;
