// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'headerFloatRightItem': string;
  'headerUserSubMenu': string;
  'headerUserSubMenuItem': string;
  'menu': string;
  'pageTitle': string;
  'pageTitleLogo': string;
  'textContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
