// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footerLayout': string;
  'githubIcon': string;
  'link': string;
}
export const cssExports: CssExports;
export default cssExports;
