/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/': {
    get: operations['redirect_to_docs__get'];
  };
  '/api/v1/admin/users': {
    get: operations['list_users_api_v1_admin_users_get'];
    post: operations['create_user_api_v1_admin_users_post'];
  };
  '/api/v1/admin/users/{uid}': {
    delete: operations['delete_user_api_v1_admin_users__uid__delete'];
  };
  '/api/v1/admin/domain_users': {
    get: operations['list_domain_users_api_v1_admin_domain_users_get'];
  };
  '/api/v1/admin/domain_roles': {
    get: operations['list_domain_roles_api_v1_admin_domain_roles_get'];
  };
  '/api/v1/version': {
    get: operations['version_api_v1_version_get'];
  };
  '/api/v1/jwt': {
    get: operations['jwt_api_v1_jwt_get'];
  };
  '/api/v1/domains': {
    /**
     * List all domains in which {user} has a role.
     * Use current login user if {user} is not specified.
     */
    get: operations['list_domains_api_v1_domains_get'];
    post: operations['create_domain_api_v1_domains_post'];
  };
  '/api/v1/domains/{domain}': {
    get: operations['get_domain_api_v1_domains__domain__get'];
    delete: operations['delete_domain_api_v1_domains__domain__delete'];
    patch: operations['update_domain_api_v1_domains__domain__patch'];
  };
  '/api/v1/domains/{domain}/members': {
    get: operations['list_members_in_domain_api_v1_domains__domain__members_get'];
  };
  '/api/v1/domains/{domain}/members/{uid}': {
    post: operations['add_member_to_domain_api_v1_domains__domain__members__uid__post'];
    delete: operations['remove_member_from_domain_api_v1_domains__domain__members__uid__delete'];
  };
  '/api/v1/domains/{domain}/labels': {
    get: operations['list_labels_in_domain_api_v1_domains__domain__labels_get'];
  };
  '/api/v1/problems': {
    get: operations['list_problems_api_v1_problems_get'];
    post: operations['create_problem_api_v1_problems_post'];
  };
  '/api/v1/problems/{problem}': {
    get: operations['get_problem_api_v1_problems__problem__get'];
    delete: operations['delete_problem_api_v1_problems__problem__delete'];
    patch: operations['update_problem_api_v1_problems__problem__patch'];
  };
  '/api/v1/problems/{problem}/clone': {
    post: operations['clone_problem_api_v1_problems__problem__clone_post'];
  };
  '/api/v1/problems/{problem_set}/{problem}': {
    put: operations['add_problem_to_problem_set_api_v1_problems__problem_set___problem__put'];
    post: operations['submit_solution_to_problem_api_v1_problems__problem_set___problem__post'];
    delete: operations['delete_problem_from_problem_set_api_v1_problems__problem_set___problem__delete'];
  };
  '/api/v1/problem_sets': {
    get: operations['list_problem_sets_api_v1_problem_sets_get'];
    post: operations['create_problem_set_api_v1_problem_sets_post'];
  };
  '/api/v1/problem_sets/{problem_set}': {
    get: operations['get_problem_set_api_v1_problem_sets__problem_set__get'];
    delete: operations['delete_problem_set_api_v1_problem_sets__problem_set__delete'];
    patch: operations['update_problem_set_api_v1_problem_sets__problem_set__patch'];
  };
  '/api/v1/problem_groups': {
    get: operations['list_problem_groups_api_v1_problem_groups_get'];
  };
  '/api/v1/problem_groups/{problem_group}': {
    get: operations['get_problems_in_problem_group_api_v1_problem_groups__problem_group__get'];
  };
  '/api/v1/records': {
    get: operations['list_records_api_v1_records_get'];
  };
  '/api/v1/records/{record}': {
    get: operations['get_record_api_v1_records__record__get'];
  };
  '/api/v1/records/{record}/code': {
    get: operations['get_record_code_api_v1_records__record__code_get'];
  };
  '/api/v1/user/logout': {
    get: operations['logout_api_v1_user_logout_get'];
  };
  '/api/v1/user/jaccount/login': {
    get: operations['jaccount_login_api_v1_user_jaccount_login_get'];
  };
  '/api/v1/user/jaccount/auth': {
    get: operations['jaccount_auth_api_v1_user_jaccount_auth_get'];
  };
  '/api/v1/user': {
    get: operations['get_user_api_v1_user_get'];
  };
  '/api/v1/user/domains': {
    get: operations['get_user_domains_api_v1_user_domains_get'];
  };
  '/api/v1/user/problems': {
    get: operations['get_user_problems_api_v1_user_problems_get'];
  };
  '/api/v1/users/{uid}': {
    get: operations['get_user_api_v1_users__uid__get'];
  };
  '/api/v1/users/{uid}/domains': {
    get: operations['get_user_domains_api_v1_users__uid__domains_get'];
  };
  '/api/v1/users/{uid}/problems': {
    get: operations['get_user_problems_api_v1_users__uid__problems_get'];
  };
}

export interface components {
  schemas: {
    CodeFile: {
      code_type: components['schemas']['RecordCodeType'];
      file: string;
    };
    Domain: {
      id?: string;
      /** (unique) url of the domain */
      url: string;
      /** displayed name of the domain */
      name: string;
      /** bulletin of the domain */
      bulletin?: string;
      /** gravatar url of the domain */
      gravatar?: string;
      owner: Partial<string> & Partial<components['schemas']['UserBase']>;
    };
    DomainCreate: {
      /** (unique) url of the domain */
      url: string;
      /** displayed name of the domain */
      name: string;
      /** bulletin of the domain */
      bulletin?: string;
      /** gravatar url of the domain */
      gravatar?: string;
    };
    DomainEdit: {
      name?: string;
      gravatar?: string;
      bulletin?: string;
    };
    DomainRole: {
      id?: string;
      domain: Partial<string> & Partial<components['schemas']['Domain']>;
      role: string;
      permission?: { [key: string]: any };
      updated_at?: string;
    };
    DomainUser: {
      id?: string;
      domain: Partial<string> & Partial<components['schemas']['Domain']>;
      user: Partial<string> & Partial<components['schemas']['UserBase']>;
      role: string;
      join_at?: string;
    };
    HTTPValidationError: {
      detail?: components['schemas']['ValidationError'][];
    };
    JWT: {
      jwt: string;
    };
    Problem: {
      id?: string;
      domain: Partial<string> & Partial<components['schemas']['Domain']>;
      /** title of the problem */
      title: string;
      /** content of the problem */
      content?: string;
      /** whether the problem is hidden */
      hidden?: boolean;
      /** acceptable language of the problem */
      languages?: string[];
      owner: Partial<string> & Partial<components['schemas']['UserBase']>;
      group: Partial<string> & Partial<components['schemas']['ProblemGroup']>;
      num_submit?: number;
      num_accept?: number;
      data?: number;
      data_version?: number;
    };
    ProblemCreate: {
      /** url or the id of the domain */
      domain: string;
      /** title of the problem */
      title: string;
      /** content of the problem */
      content?: string;
      /** whether the problem is hidden */
      hidden?: boolean;
      /** acceptable language of the problem */
      languages?: string[];
    };
    ProblemEdit: {
      title?: string;
      content?: string;
      hidden?: boolean;
      data?: number;
      data_version?: number;
      languages?: string[];
    };
    ProblemGroup: {
      id?: string;
      moss_results?: string[];
    };
    ProblemSet: {
      id?: string;
      domain: Partial<string> & Partial<components['schemas']['Domain']>;
      /** title of the problem set */
      title: string;
      /** content of the problem set */
      content?: string;
      /** whether the problem set is hidden */
      hidden?: boolean;
      problems?: (Partial<string> &
        Partial<components['schemas']['Problem']>)[];
      owner: Partial<string> & Partial<components['schemas']['UserBase']>;
      labels?: string[];
      num_submit?: number;
      num_accept?: number;
    };
    ProblemSetCreate: {
      /** url or the id of the domain */
      domain: string;
      /** title of the problem set */
      title: string;
      /** content of the problem set */
      content?: string;
      /** whether the problem set is hidden */
      hidden?: boolean;
      /** problems belonging to the problem set */
      problems?: string[];
    };
    ProblemSetEdit: {
      title?: string;
      content?: string;
      hidden?: boolean;
      labels?: string[];
      problems?: (Partial<string> &
        Partial<components['schemas']['Problem']>)[];
    };
    Record: {
      id?: string;
      status?: components['schemas']['RecordStatus'];
      score?: number;
      time_ms?: number;
      memory_kb?: number;
      domain: Partial<string> & Partial<components['schemas']['Domain']>;
      problem: Partial<string> & Partial<components['schemas']['Problem']>;
      problem_set: Partial<string> &
        Partial<components['schemas']['ProblemSet']>;
      problem_data?: number;
      user: Partial<string> & Partial<components['schemas']['UserBase']>;
      code_type: components['schemas']['RecordCodeType'];
      code: string;
      judge_category: string[];
      submit_at: string;
      judge_at: string;
      judge_user: Partial<string> & Partial<components['schemas']['UserBase']>;
      compiler_texts?: string;
    };
    /** An enumeration. */
    RecordCodeType: 0 | 1 | 2 | 3;
    /** An enumeration. */
    RecordStatus:
      | 0
      | 1
      | 2
      | 3
      | 4
      | 5
      | 6
      | 7
      | 8
      | 9
      | 10
      | 20
      | 21
      | 22
      | 30;
    RedirectModel: {
      redirect_url: string;
    };
    User: {
      id?: string;
      scope: string;
      uname: string;
      mail: string;
      uname_lower?: string;
      mail_lower?: string;
      gravatar?: string;
      salt?: string;
      hash?: string;
      role?: string;
      student_id?: string;
      real_name?: string;
      register_ip?: string;
      login_ip?: string;
      register_timestamp: string;
      login_timestamp: string;
    };
    UserBase: {
      id?: string;
      scope: string;
      uname: string;
      mail: string;
      uname_lower?: string;
      mail_lower?: string;
      gravatar?: string;
    };
    ValidationError: {
      loc: string[];
      msg: string;
      type: string;
    };
    Version: {
      version: string;
      git: string;
    };
  };
}

export interface operations {
  redirect_to_docs__get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': { [key: string]: any };
        };
      };
    };
  };
  list_users_api_v1_admin_users_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['User'][];
        };
      };
    };
  };
  create_user_api_v1_admin_users_post: {
    parameters: {
      query: {
        student_id: string;
        jaccount_name: string;
        real_name: string;
        ip: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_user_api_v1_admin_users__uid__delete: {
    parameters: {
      path: {
        uid: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_domain_users_api_v1_admin_domain_users_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DomainUser'][];
        };
      };
    };
  };
  list_domain_roles_api_v1_admin_domain_roles_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DomainRole'][];
        };
      };
    };
  };
  version_api_v1_version_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Version'];
        };
      };
    };
  };
  jwt_api_v1_jwt_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['JWT'];
        };
      };
    };
  };
  /**
   * List all domains in which {user} has a role.
   * Use current login user if {user} is not specified.
   */
  list_domains_api_v1_domains_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Domain'][];
        };
      };
    };
  };
  create_domain_api_v1_domains_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Domain'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DomainCreate'];
      };
    };
  };
  get_domain_api_v1_domains__domain__get: {
    parameters: {
      path: {
        domain: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Domain'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_domain_api_v1_domains__domain__delete: {
    parameters: {
      path: {
        domain: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_domain_api_v1_domains__domain__patch: {
    parameters: {
      path: {
        domain: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Domain'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DomainEdit'];
      };
    };
  };
  list_members_in_domain_api_v1_domains__domain__members_get: {
    parameters: {
      path: {
        domain: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DomainUser'][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_member_to_domain_api_v1_domains__domain__members__uid__post: {
    parameters: {
      path: {
        /** url or ObjectId of the domain */
        domain: string;
        uid: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_member_from_domain_api_v1_domains__domain__members__uid__delete: {
    parameters: {
      path: {
        /** url or ObjectId of the domain */
        domain: string;
        uid: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_labels_in_domain_api_v1_domains__domain__labels_get: {
    parameters: {
      path: {
        /** url or ObjectId of the domain */
        domain: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': string[];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_problems_api_v1_problems_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'][];
        };
      };
    };
  };
  create_problem_api_v1_problems_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProblemCreate'];
      };
    };
  };
  get_problem_api_v1_problems__problem__get: {
    parameters: {
      path: {
        problem: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_problem_api_v1_problems__problem__delete: {
    parameters: {
      path: {
        problem: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_problem_api_v1_problems__problem__patch: {
    parameters: {
      path: {
        problem: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProblemEdit'];
      };
    };
  };
  clone_problem_api_v1_problems__problem__clone_post: {
    parameters: {
      path: {
        problem: string;
      };
      query: {
        /** url or the id of the domain */
        domain: string;
        /** create new problem group or use the original one */
        new_group?: boolean;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  add_problem_to_problem_set_api_v1_problems__problem_set___problem__put: {
    parameters: {
      path: {
        problem_set: string;
        problem: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProblemSet'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_solution_to_problem_api_v1_problems__problem_set___problem__post: {
    parameters: {
      path: {
        problem_set: string;
        problem: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Record'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['CodeFile'];
      };
    };
  };
  delete_problem_from_problem_set_api_v1_problems__problem_set___problem__delete: {
    parameters: {
      path: {
        problem_set: string;
        problem: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_problem_sets_api_v1_problem_sets_get: {
    parameters: {
      query: {
        required_labels?: string[];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProblemSet'][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_problem_set_api_v1_problem_sets_post: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProblemSet'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProblemSetCreate'];
      };
    };
  };
  get_problem_set_api_v1_problem_sets__problem_set__get: {
    parameters: {
      path: {
        problem_set: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProblemSet'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_problem_set_api_v1_problem_sets__problem_set__delete: {
    parameters: {
      path: {
        problem_set: string;
      };
    };
    responses: {
      /** Successful Response */
      204: never;
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_problem_set_api_v1_problem_sets__problem_set__patch: {
    parameters: {
      path: {
        problem_set: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProblemSet'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProblemSetEdit'];
      };
    };
  };
  list_problem_groups_api_v1_problem_groups_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['ProblemGroup'][];
        };
      };
    };
  };
  get_problems_in_problem_group_api_v1_problem_groups__problem_group__get: {
    parameters: {
      path: {
        problem_group: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_records_api_v1_records_get: {
    parameters: {
      query: {
        /** uid or 'me' or empty */
        uid?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Record'][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_record_api_v1_records__record__get: {
    parameters: {
      path: {
        record: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Record'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_record_code_api_v1_records__record__code_get: {
    parameters: {
      path: {
        record: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': { [key: string]: any };
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_user_logout_get: {
    parameters: {
      query: {
        /** Set the redirect url after the logout. */
        redirect_url?: string;
        /** If true (html link mode), redirect to a url; If false (ajax mode), return the redirect url, you also need to unset all cookies manually in ajax mode. */
        redirect?: boolean;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['RedirectModel'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  jaccount_login_api_v1_user_jaccount_login_get: {
    parameters: {
      query: {
        /** Set the redirect url after the authorization. */
        redirect_url?: string;
        /** If true (html link mode), redirect to jaccount site; If false (ajax mode), return the redirect url to the jaccount site, you also need to set the cookies returned manually in ajax mode. */
        redirect?: boolean;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['RedirectModel'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  jaccount_auth_api_v1_user_jaccount_auth_get: {
    parameters: {
      query: {
        state: string;
        code: string;
      };
      cookie: {
        jaccount_state?: string;
        redirect_url?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': { [key: string]: any };
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_api_v1_user_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['User'];
        };
      };
    };
  };
  get_user_domains_api_v1_user_domains_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DomainUser'][];
        };
      };
    };
  };
  get_user_problems_api_v1_user_problems_get: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'][];
        };
      };
    };
  };
  get_user_api_v1_users__uid__get: {
    parameters: {
      path: {
        uid: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['UserBase'];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_domains_api_v1_users__uid__domains_get: {
    parameters: {
      path: {
        uid: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['DomainUser'][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_user_problems_api_v1_users__uid__problems_get: {
    parameters: {
      path: {
        uid: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          'application/json': components['schemas']['Problem'][];
        };
      };
      /** Validation Error */
      422: {
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
}
