// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'domainLayoutHeader': string;
  'pageBody': string;
  'pageContentNoHeader': string;
  'pageContentWithHeader': string;
  'pageFooter': string;
  'pageHeader': string;
  'pageLayout': string;
  'pageTitle': string;
  'pageTitleLogo': string;
}
export const cssExports: CssExports;
export default cssExports;
